services:
  Api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: event_api
    container_name: event_api_container 
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: db_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: EventDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d EventDB"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: